@apiURL = http://localhost:8080/products

@token = superhemligt

###

POST {{apiURL}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_name": "Sunflower",
    "price": 14.50,
    "img": "sunflower.jpg",
    "description_text": "sunflower",
    "quantity": 4
}

###

PUT {{apiURL}}/12
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_name": "Tulip",
    "price": 300,
    "img": "rose_red.jpg",
    "description_text": "pretty flower"
}

###

DELETE {{apiURL}}/15
Authorization: Bearer {{token}}

###

POST http://localhost:8080/products/8/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="rose.jpg"
Content-Type: image/jpeg

< ./rose.jpg
--boundary--